"""remove kpi id

Revision ID: 36651e8549c9
Revises: 6ef970590760
Create Date: 2024-06-19 14:22:50.681691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36651e8549c9'
down_revision = '6ef970590760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_constraint('responses_kpi_id_fkey', type_='foreignkey')
        batch_op.drop_column('kpi_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kpi_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('responses_kpi_id_fkey', 'key_performance_indicators', ['kpi_id'], ['id'])

    # ### end Alembic commands ###
