"""feat: sender column

Revision ID: 3b14489646c2
Revises: 8765933bda1f
Create Date: 2024-06-24 21:02:40.231974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b14489646c2'
down_revision = '8765933bda1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender', sa.String(length=10), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['sender'], ['role'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sender')

    # ### end Alembic commands ###
