"""feat: new models

Revision ID: 549d2cc2223c
Revises: 835949b76c00
Create Date: 2024-06-11 12:45:25.033453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '549d2cc2223c'
down_revision = '835949b76c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigned_merchandisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('merchandiser_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merchandiser_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=200), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchandiser_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('response', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merchandiser_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('key_performance_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('performance_metric', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchandiser_performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchandiser_id', sa.Integer(), nullable=False),
    sa.Column('k_p_i_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('day', sa.String(length=50), nullable=False),
    sa.Column('performance', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['k_p_i_id'], ['key_performance_indicators.id'], ),
    sa.ForeignKeyConstraint(['merchandiser_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodic_performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchandiser_id', sa.Integer(), nullable=False),
    sa.Column('merchandiser_performance_id', sa.Integer(), nullable=False),
    sa.Column('day', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('week', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('month', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('year', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['merchandiser_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merchandiser_performance_id'], ['merchandiser_performances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('outlets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outlets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('contact_info', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('street', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='outlets_pkey')
    )
    op.drop_table('periodic_performances')
    op.drop_table('merchandiser_performances')
    op.drop_table('key_performance_indicators')
    op.drop_table('responses')
    op.drop_table('facilities')
    op.drop_table('assigned_merchandisers')
    # ### end Alembic commands ###
