"""feat: reduce tables

Revision ID: 99ec2a529fa0
Revises: c23d74761bf5
Create Date: 2024-06-18 13:42:21.397502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99ec2a529fa0'
down_revision = 'c23d74761bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_merchandisers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchandisers_id', postgresql.JSON(astext_type=sa.Text()), nullable=False))
        batch_op.add_column(sa.Column('date_time', sa.DateTime(), nullable=False))
        batch_op.drop_constraint('assigned_merchandisers_merchandiser_id_fkey', type_='foreignkey')
        batch_op.drop_column('merchandiser_id')
        batch_op.drop_column('year')
        batch_op.drop_column('month')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_merchandisers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('merchandiser_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('assigned_merchandisers_merchandiser_id_fkey', 'users', ['merchandiser_id'], ['id'])
        batch_op.drop_column('date_time')
        batch_op.drop_column('merchandisers_id')

    # ### end Alembic commands ###
