"""key performance indicators

Revision ID: c23d74761bf5
Revises: f1c978a489d8
Create Date: 2024-06-13 13:48:01.273179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23d74761bf5'
down_revision = 'f1c978a489d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_performance_indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('key_performance_indicators_facility_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'])
        batch_op.drop_column('facility_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_performance_indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('key_performance_indicators_facility_id_fkey', 'facilities', ['facility_id'], ['id'])
        batch_op.drop_column('admin_id')
        batch_op.drop_column('company_name')
        batch_op.drop_column('sector_name')

    # ### end Alembic commands ###
