"""new columns

Revision ID: dc6b05e3b6d4
Revises: 36651e8549c9
Create Date: 2024-06-20 12:36:30.856962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc6b05e3b6d4'
down_revision = '36651e8549c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_plan_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('instruction_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_column('instruction_id')
        batch_op.drop_column('route_plan_id')

    # ### end Alembic commands ###
